---
- name: copy containerd config
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: modprobe commands
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: copy kube sysctl conf
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: reload sysctl.conf vars
  command: sysctl --system
